Adding Digital Ocean droplet creation & config instructions
UWB-ACM/Hackathon-Docs pull request #6
Opened 2019-03-12 01:51 UTC by etcadinfinitum

- [x] Create DO account
- [x] Create DO droplet
- [ ] Create non-root account on droplet
- [ ] Add ssh keys to droplet (after droplet has been created)
- [ ] Might also need `ssh-keygen` instructions?
- [ ] Test login abilities via SSH

Not sure what else should belong in this section. I think web server config should be written up separately.

2019-04-02 01:48 UTC, Chris-Johnston requested changes
just a few things that I would add

2019-04-02 01:48 UTC, Chris-Johnston commented on Server-Creation.md
> +  - A credit or debit card to link to the account
We should mention here that student credits are a thing, and that if you use them it won't cost anything

https://www.digitalocean.com/community/questions/student-discounts

2019-04-02 01:48 UTC, Chris-Johnston commented on Server-Creation.md
> +A **Droplet** is a fancy term Digital Ocean (DO) came up with; fundamentally, it is a remote machine that they provide hardware and infrastructure for. A droplet that you create can be used to deploy
```suggestion
A **Droplet** is a fancy term Digital Ocean (DO) came up with; fundamentally, it is a remote virtual machine that they provide hardware and infrastructure for. A droplet that you create can be used to deploy websites, run bots, build and run large projects, or anything else you want. 
```

2019-04-02 01:48 UTC, Chris-Johnston commented on Server-Creation.md
> +After the droplet is created, you will receive an email with credentials for your droplet's `root` account. The email will look something like this:
missing screenshot?

2019-04-02 01:48 UTC, Chris-Johnston commented on Server-Creation.md
> +On first login, you will be required to change the password for `root`. Make it something memorable!
may be important to note that no characters will be shown when typing in password

2019-04-03 01:45 UTC, etcadinfinitum commented on Server-Creation.md
> +  - A credit or debit card to link to the account
Yes! I will add this

2019-04-04 22:14 UTC, etcadinfinitum commented on Server-Creation.md
> +On first login, you will be required to change the password for `root`. Make it something memorable!
Added

2019-04-04 22:17 UTC, etcadinfinitum commented on Server-Creation.md
> +After the droplet is created, you will receive an email with credentials for your droplet's `root` account. The email will look something like this:
I removed that sentence. Good catch. I decided to omit screenshots because the process isn't so complicated as to necessitate it.

2019-04-04 22:23 UTC, merged